### ISSUE TITLE
scale_fill_manual appears not to be working

### ISSUE THREAD

**Issue by lizmckenna** [p3lab/p3themes#2]
https://github.com/p3lab/p3themes/blob/d334a7f9a2e7a1743c6b4bf9c686a3571b4ef759/examples/example-1#L43

@jaeyk any Idea why all the text formatting is working when I call the p3 theme but the fill color is not?

**Comment by jaeyk** [comment]
@lizmckenna Corrected a typo in the r script with a new commit.

**Comment by jaeyk** [comment]
@lizmckenna I will also reformat the example files you created later on.

**Comment by lizmckenna** [comment]
@jaeyk yes, no rush!!
