### ISSUE TITLE
need scale_color_manual specification too?

### ISSUE THREAD

**Issue by lizmckenna** [p3lab/p3themes#4]
https://github.com/p3lab/p3themes/blob/d877c884b68791ba2248a9ca2cef0ab261bdf2cb/R/p3theme.R#L19

@jaeyk I don't want to mess anything up but can we also specify the P3 colors in a scale_color_manual function too? I just did the below and the colors remained the default ggplot pink and blue I think because I used color and not fill in the aesthetic

```
# Line plot just the PFML tags
b <- ggplot(subset(df, hashtag %in% c("PaidLeaveMN", "WhoCaresForUs")),
            aes(x=date, color=hashtag)) + geom_line(stat="count") + theme_bw()
b

b1 <- b+ labs(y = "Date 2021",
       x = "Count",
       title = "PFML Hashtag Usage During 2021 MN Legislative Session")
b1
```

# Clean up the plot
b2 <- add_p3theme(b1)
b2`
![Rplot](https://user-images.githubusercontent.com/13068609/119037834-5001d700-b967-11eb-8290-8712d038fd94.png)

**Comment by jaeyk** [comment]
@lizmckenna This is actually a good point. I will take a look at this either tomorrow or early next week. Does that timeframe work for you?

**Comment by jaeyk** [comment]
The new commit addressed this problem. I will update the vignette as well.

**Comment by jaeyk** [comment]
Updated the website.
